# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9a2cb1b2ac326540403c8b556f6649c9533bb8e9882221706a8d11dd9b72894683538c539e1afacdebc919aba7a8be15caa003ad65835d82703327904e29bd0

test:
  secret_key_base: 0cf7ad07130ecfc2fd618ed138afbd70f0aeed7a871244f60cde14e07c2009d19aca1e42a700ac3b7de3f38805eb33d9348690e7846da8453e5f9037e9ac2a13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
